include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    avoid_print: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
